apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::568906074149:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-131K5N9RENLJ7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::568906074149:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-26T01:09:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2122"
  uid: 248a1053-5dbc-4abe-9956-25a428b36521
